'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_PREVISION_ACTIVO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_PREVISION_ACTIVO
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_PREVISION_ACTIVO
    End Sub
    Function IRIS_WEBF_BUSCA_PREVISION_ACTIVO() As List(Of E_IRIS_WEBF_BUSCA_PREVISION_ACTIVO)
        Return DD_Data.IRIS_WEBF_BUSCA_PREVISION_ACTIVO()
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_PREVISION_ACTIVO_Y_PARTICULAR() As List(Of E_IRIS_WEBF_BUSCA_PREVISION_ACTIVO)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_PREVISION_ACTIVO_Y_PARTICULAR()
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_PREVISION_ACTIVO_TODO_Y_PARTICULAR() As List(Of E_IRIS_WEBF_BUSCA_PREVISION_ACTIVO)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_PREVISION_ACTIVO_TODO_Y_PARTICULAR()
    End Function

    Function IRIS_WEBF_BUSCA_PREVISION_PROCEDENCIA_ACTIVO(ByVal ID_PROC As Integer) As List(Of E_IRIS_WEBF_BUSCA_PREVISION_ACTIVO)
        Return DD_Data.IRIS_WEBF_BUSCA_PREVISION_PROCEDENCIA_ACTIVO(ID_PROC)
    End Function
End Class