Imports Entidades
Imports Datos
Imports System.Collections.Generic

Public Class N_IRIS_WEBF_BUSCA_AREA
    Dim DD_Data As D_IRIS_WEBF_BUSCA_AREA
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_AREA
    End Sub
    Function IRIS_WEBF_BUSCA_AREA() As List(Of E_IRIS_WEBF_BUSCA_AREA)
        Return DD_Data.IRIS_WEBF_BUSCA_AREA()
    End Function

    Function LLENAR_DDL_SECCION() As List(Of E_IRIS_WEBF_BUSCA_RELACION_AREA_SECCION_ESTADO)
        Return DD_Data.IRIS_WEBF_LLENAR_DLL_SECCION()
    End Function


    Function IRIS_WEBF_BUSCA_RELACION_AREA_SECCION_NO_RELACIONADAS(ByVal ID_AREA As Integer) As List(Of E_IRIS_WEBF_BUSCA_SECCION)
        Return DD_Data.IRIS_WEBF_BUSCA_RELACION_AREA_SECCION_NO_RELACIONADAS(ID_AREA)
    End Function


    Function IRIS_WEBF_BUSCA_RELACION_AREA_SECCION_ESTADO(ByVal ID_AREA As Integer) As List(Of E_IRIS_WEBF_BUSCA_RELACION_AREA_SECCION_ESTADO)
        Return DD_Data.IRIS_WEBF_BUSCA_RELACION_AREA_SECCION_ESTADO(ID_AREA)
    End Function


    Function IRIS_WEBF_GRABA_RELACION_AREA_SECCION(ByVal ID_AREA As Integer, ByVal ARRAY_SECCION As Integer) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_RELACION_AREA_SECCION(ID_AREA, ARRAY_SECCION)
    End Function

    Function IRIS_WEBF_UPDATE_REL_AREA_SECCION_QUITAR_RELACION(ByVal ARRAY_SECCION As Integer) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_REL_AREA_SECCION_QUITAR_RELACION(ARRAY_SECCION)
    End Function
End Class
