Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS_DERIVADOS
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS_DERIVADOS
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS_DERIVADOS
    End Sub
    Function IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS_DERIVADOS() As List(Of E_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS_DERIVADOS)
        Return DD_Data.IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS_DERIVADOS()
    End Function
End Class
