'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS
    End Sub
    Function IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS() As List(Of E_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS)
        Return DD_Data.IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS()
    End Function
    Function IRIS_WEBF_BUSCA_CB_DESC_TODOS() As List(Of E_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS)
        Return DD_Data.IRIS_WEBF_BUSCA_CB_DESC_TODOS()
    End Function

    Function IRIS_WEBF_BUSCA_TP_VALORES_CRITICOS_ACTIVOS() As List(Of E_IRIS_WEBF_BUSCA_EST_CODIGO_FONASA_ACTIVOS)
        Return DD_Data.IRIS_WEBF_BUSCA_TP_VALORES_CRITICOS_ACTIVOS()
    End Function

End Class
