'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_COSTOS_ACTIVOS_DESACTIVOS
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_COSTOS_ACTIVOS_DESACTIVOS
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_COSTOS_ACTIVOS_DESACTIVOS
    End Sub
    Function IRIS_WEBF_BUSCA_COSTOS_ACTIVOS_DESACTIVOS() As List(Of E_IRIS_WEBF_BUSCA_COSTOS_ACTIVOS_DESACTIVOS)
        Return DD_Data.IRIS_WEBF_BUSCA_COSTOS_ACTIVOS_DESACTIVOS()
    End Function
End Class
