'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_BUSCA_ESTADO_DETERMINACION_RECEPCION_MUESTRA_RECHAZO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_ESTADO_DETERMINACION_RECEPCION_MUESTRA_RECHAZO

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_ESTADO_DETERMINACION_RECEPCION_MUESTRA_RECHAZO
    End Sub

    Function IRIS_WEBF_BUSCA_ESTADO_DETERMINACION_RECEPCION_MUESTRA_RECHAZO(ByVal ID_ATE As Integer, ByVal ID_PER As Integer, ByVal CB As String) As List(Of E_IRIS_WEBF_BUSCA_ESTADO_DETERMINACION_RECEPCION_MUESTRA_RECHAZO)
        Return DD_Data.IRIS_WEBF_BUSCA_ESTADO_DETERMINACION_RECEPCION_MUESTRA_RECHAZO(ID_ATE, ID_PER, CB)

    End Function
End Class