'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_RECHAZO_INSERTA_RECHAZO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_RECHAZO_INSERTA_RECHAZO

    Sub New()
        DD_Data = New D_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_RECHAZO_INSERTA_RECHAZO
    End Sub

    Function IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_RECHAZO_INSERTA_RECHAZO(ByVal ID_ATE As Integer, ByVal VALOR As String) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_RECHAZO_INSERTA_RECHAZO(ID_ATE, VALOR)

    End Function
End Class