'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO
    End Sub

    Function IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO(ByVal NUM_ATE As String, ByVal CB As String) As List(Of E_IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO)
        Return DD_Data.IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO(NUM_ATE, CB)

    End Function


    Function IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO_2(ByVal NUM_ATE As String, ByVal CB As String) As List(Of E_IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO)
        Return DD_Data.IRIS_WEBF_BUSCA_ETIQUETA_BARRA_PACIENTE_RECEP_RECHAZO_2(NUM_ATE, CB)

    End Function
End Class