'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_BUSCA_ETIQUETAS_EXAMENES_DESC_RECEPCION_RECHAZO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_ETIQUETAS_EXAMENES_DESC_RECEPCION_RECHAZO

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_ETIQUETAS_EXAMENES_DESC_RECEPCION_RECHAZO
    End Sub

    Function IRIS_WEBF_BUSCA_ETIQUETAS_EXAMENES_DESC_RECEPCION_RECHAZO(ByVal NUM_ATE As Integer, ByVal CB As String) As List(Of E_IRIS_WEBF_BUSCA_ETIQUETAS_EXAMENES_DESC_RECEPCION_RECHAZO)
        Return DD_Data.IRIS_WEBF_BUSCA_ETIQUETAS_EXAMENES_DESC_RECEPCION_RECHAZO(NUM_ATE, CB)

    End Function
End Class