
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_NO_ASOC
    Dim DD_Data As D_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_NO_ASOC
    Sub New()
        DD_Data = New D_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_NO_ASOC
    End Sub
    'Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_NO_ASOC(ByVal DESDE As String, ByVal HASTA As String) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
    '    Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_NO_ASOC(DESDE, HASTA)
    'End Function
End Class