Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER
    Dim DD_Data As D_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER
    Sub New()
        DD_Data = New D_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER
    End Sub
    'Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE(ByVal ID_ATENCION As Long) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
    '    Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE(ID_ATENCION)
    'End Function
    Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2(ByVal ID_ATENCION As Long) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2(ID_ATENCION)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_PDF(ByVal ID_ATENCION As Long) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_PDF(ID_ATENCION)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_PDF_PREI(ByVal PREI_NUM As Long) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_PDF_PREI(PREI_NUM)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_PDF_ATE_PREI(ByVal PREI_NUM As Long, ByVal ATE_NUM As Long) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_PDF_ATE_PREI(PREI_NUM, ATE_NUM)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_ASOC(ByVal DESDE As String, ByVal HASTA As String) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_ASOC(DESDE, HASTA)
    End Function

    Function IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_ASOC_PDF(ByVal DESDE As String, ByVal HASTA As String) As List(Of E_IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_IMAGEN_SCANNER_MOBILE_2_ASOC_PDF(DESDE, HASTA)
    End Function

    Function IRIS_WEBF_CMVM_GRABA_IMAGEN_MOBILE_ASOC(ByVal ID_USUARIO As Integer, ByVal ID_ATENCION As Long, ByVal ATE_NUM As String, ByVal IMG As Long) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_IMAGEN_MOBILE_ASOC(ID_USUARIO, ID_ATENCION, ATE_NUM, IMG)
    End Function
    Function IRIS_WEBF_CMVM_GRABA_IMAGEN_MOBILE_ASOC_PREI(ByVal ID_USUARIO As Integer, ByVal ID_ATENCION As Long, ByVal ATE_NUM As String, ByVal ID_PREINGRESO As Long,
                                            ByVal PREI_NUM As String, ByVal IMG As Long) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_IMAGEN_MOBILE_ASOC_PREI(ID_USUARIO, ID_ATENCION, ATE_NUM, ID_PREINGRESO, PREI_NUM, IMG)
    End Function

    Function IRIS_WEBF_CMVM_ELIMINA_IMAGEN_MOBILE_ASOC(ByVal ID_FOTO_ATE As Integer) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_ELIMINA_IMAGEN_MOBILE_ASOC(ID_FOTO_ATE)
    End Function
    Function IRIS_WEBF_CMVM_ELIMINA_IMAGEN_MOBILE(ByVal ID_FOTO_ATE As Integer) As String
        Return DD_Data.IRIS_WEBF_CMVM_ELIMINA_IMAGEN_MOBILE(ID_FOTO_ATE)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_FOLIO_ID_ATE(ByVal ID_ATENCION As Integer) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_FOLIO_ID_ATE(ID_ATENCION)
    End Function

End Class
