Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_CMVM_BUSCA_COUNT_PAC_DOCS_2
    Dim DD_Data As D_IRIS_WEBF_CMVM_BUSCA_COUNT_PAC_DOCS_2
    Sub New()
        DD_Data = New D_IRIS_WEBF_CMVM_BUSCA_COUNT_PAC_DOCS_2
    End Sub

    Function IRIS_WEBF_CMVM_BUSCA_COUNT_PAC_DOCS_2_MOBILE(ByVal DESDE As String, ByVal HASTA As String) As List(Of E_IRIS_WEBF_CMVM_BUSCA_COUNT_PAC_DOCS_2)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_COUNT_PAC_DOCS_2_MOBILE(DESDE, HASTA)
    End Function
End Class
