Imports Datos
Imports Entidades
Public Class N_Ate_Det
    'Declaraciones Generales
    Dim DD_Ate_Det As D_Ate_Det
    Sub New()
        DD_Ate_Det = New D_Ate_Det
    End Sub
    Function IRIS_WEBF_BUSCA_ID_ATENCION_POR_NUMERO_DE_ATENCION() As List(Of E_IRIS_WEBF_BUSCA_ID_ATENCION_POR_NUMERO_DE_ATENCION)
        Return DD_Ate_Det.IRIS_WEBF_BUSCA_ID_ATENCION_POR_NUMERO_DE_ATENCION
    End Function
    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES4(ByVal ID_ATE As Long) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES4)
        Return DD_Ate_Det.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES4(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR(ByVal ID_ATE As Long) As List(Of E_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR)
        Return DD_Ate_Det.IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_DETALLE_ATENCION3(ByVal ID_ATE As Long) As List(Of E_IRIS_WEBF_BUSCA_DETALLE_ATENCION3)
        Return DD_Ate_Det.IRIS_WEBF_BUSCA_DETALLE_ATENCION3(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCAR_RUTA_PDF_DER(ByVal ID_ATE As Long, ByVal ID_CF As Long) As List(Of E_IRIS_WEBF_BUSCAR_RUTA_PDF_DER)
        Return DD_Ate_Det.IRIS_WEBF_BUSCAR_RUTA_PDF_DER(ID_ATE, ID_CF)
    End Function
End Class
