'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES
    End Sub
    Function IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES(ByVal ID_PAC As Integer) As List(Of E_IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES)
        Return DD_Data.IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES(ID_PAC)
    End Function
    Function IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES_DNI(ByVal ID_PAC As Integer) As List(Of E_IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES)
        Return DD_Data.IRIS_WEBF_BUSCA_EDITAR_PACIENTE_DATOS_ACTUALES_DNI(ID_PAC)
    End Function
End Class