'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES
    End Sub
    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_AGENDA(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_AGENDA(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2_AGENDA(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2_AGENDA(ID_ATE)
    End Function


    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_AVIS_AGENDA(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_AVIS_AGENDA(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_AVIS_ATE(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES______2)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_AVIS_ATE(ID_ATE)
    End Function

End Class