'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2
    End Sub
    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2(ID_ATE)
    End Function
End Class