Imports Datos
Public Class N_IRIS_WEBF_UPDATE_CODIGO_FONASA_CONTROL_COSTO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_UPDATE_CODIGO_FONASA_CONTROL_COSTO
    Sub New()
        DD_Data = New D_IRIS_WEBF_UPDATE_CODIGO_FONASA_CONTROL_COSTO
    End Sub
    Function IRIS_WEBF_UPDATE_CODIGO_FONASA_CONTROL_COSTO(ByVal ID_CONTROL_COSTO As Integer, ByVal ID_COSTO As Integer, ByVal PRECIO As Integer, ByVal TOTAL_PRECIO As Integer) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_CODIGO_FONASA_CONTROL_COSTO(ID_CONTROL_COSTO, ID_COSTO, PRECIO, TOTAL_PRECIO)
    End Function
End Class

