
'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR
    Dim DD_Data As D_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR
    End Sub
    Function IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR(ByVal ID_ATE As Long) As List(Of E_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR)
        Return DD_Data.IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR_2(ByVal ID_ATE As Long) As List(Of E_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR)
        Return DD_Data.IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR_2(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR_PAP(ByVal ID_ATE As Long) As List(Of E_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR)
        Return DD_Data.IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR_PAP(ID_ATE)
    End Function
    Function IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR_ATE_ACT_WEB(ByVal ID_ATE As Long) As List(Of E_IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR)
        Return DD_Data.IRIS_WEBF_BUSCA_LISTADO_EXAMENES_IMPRIMIR_ATE_ACT_WEB(ID_ATE)
    End Function
End Class
