Imports Entidades
Imports Datos
Public Class N_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO
    Private DD_Data As D_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO
    Public Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO
    End Sub
    Function IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO() As List(Of E_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO)
        Return DD_Data.D_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO()
    End Function
    Function IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO_excel() As List(Of E_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO)
        Return DD_Data.IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO_excel()
    End Function
    Function IRIS_WEBF_BUSCA_TP_RESIDUO_ACTIVO() As List(Of E_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO)
        Return DD_Data.IRIS_WEBF_BUSCA_TP_RESIDUO_ACTIVO()
    End Function
    Function IRIS_WEBF_BUSCA_SECCION_RESIDUO_ACTIVO() As List(Of E_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO)
        Return DD_Data.IRIS_WEBF_BUSCA_SECCION_RESIDUO_ACTIVO()
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_PROCEDENCIA_ACTIVO_SIN_ID_USER() As List(Of E_IRIS_WEBF_BUSCA_PROCEDENCIA_ACTIVO)

        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_PROCEDENCIA_ACTIVO_SIN_ID_USER()
    End Function
End Class
