'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_DERIVA2
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_DERIVA2

    Sub New()
        DD_Data = New D_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_DERIVA2
    End Sub

    Function IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_DERIVA2(ByVal ID_ATE As Integer, ByVal ID_CF As Integer, ByVal ID_USUARIO As Integer) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION_DERIVA2(ID_ATE, ID_CF, ID_USUARIO)

    End Function
End Class
