Imports Entidades
Imports Datos
Public Class N_IRIS_GRABA_QC_RELACION_MAQ_LOTE_DETERMINACION2
    Dim DD_Data As D_IRIS_GRABA_QC_RELACION_MAQ_LOTE_DETERMINACION2
    Sub New()
        DD_Data = New D_IRIS_GRABA_QC_RELACION_MAQ_LOTE_DETERMINACION2
    End Sub
    Function IRIS_GRABA_QC_RELACION_MAQ_LOTE_DETERMINACION2(ByVal ID_ANA As Long, ByVal ID_LOTE As Long, ByVal ID_DET As Long) As Integer
        Return DD_Data.IRIS_GRABA_QC_RELACION_MAQ_LOTE_DETERMINACION2(ID_ANA, ID_LOTE, ID_DET)
    End Function
End Class
