Imports Entidades
Imports Datos
Public Class N_IRIS_BUSCA_QC_RELACION_ANALIZADOR_DET_NO_CARGADAS
    Dim DD_Data As D_IRIS_BUSCA_QC_RELACION_ANALIZADOR_DET_NO_CARGADAS
    Sub New()
        DD_Data = New D_IRIS_BUSCA_QC_RELACION_ANALIZADOR_DET_NO_CARGADAS
    End Sub
    Function IRIS_BUSCA_QC_RELACION_ANALIZADOR_DET_NO_CARGADAS(ByVal ID_ANA As Long) As List(Of E_IRIS_BUSCA_QC_RELACION_ANALIZADOR_DET_NO_CARGADAS)
        Return DD_Data.IRIS_BUSCA_QC_RELACION_ANALIZADOR_DET_NO_CARGADAS(ID_ANA)
    End Function
End Class
