Imports Entidades
Imports Datos
Public Class N_IRIS_UPDATE_QC_RELACION_MAQ_DETERMINACON_CANAL_QUITAR
    Dim DD_Data As D_IRIS_UPDATE_QC_RELACION_MAQ_DETERMINACON_CANAL_QUITAR
    Sub New()
        DD_Data = New D_IRIS_UPDATE_QC_RELACION_MAQ_DETERMINACON_CANAL_QUITAR
    End Sub
    Function IRIS_UPDATE_QC_RELACION_MAQ_DETERMINACON_CANAL_QUITAR(ByVal ID_REL As Long) As Integer

        Return DD_Data.IRIS_UPDATE_QC_RELACION_MAQ_DETERMINACON_CANAL_QUITAR(ID_REL)
    End Function
End Class
