Imports Entidades
Imports Datos
Public Class N_IRIS_UPDATE_QC_ANALIZADOR_DETERMINACION_CANAL_UPDATE
    Dim DD_Data As D_IRIS_UPDATE_QC_ANALIZADOR_DETERMINACION_CANAL_UPDATE
    Sub New()
        DD_Data = New D_IRIS_UPDATE_QC_ANALIZADOR_DETERMINACION_CANAL_UPDATE
    End Sub
    Function IRIS_UPDATE_QC_ANALIZADOR_DETERMINACION_CANAL_UPDATE(ByVal ID_REL As Long, ByVal CANAL As String) As Integer
        Return DD_Data.IRIS_UPDATE_QC_ANALIZADOR_DETERMINACION_CANAL_UPDATE(ID_REL, CANAL)
    End Function
End Class
