Imports Entidades
Imports Datos
Public Class N_IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO
    Dim DD_Data As D_IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO
    Sub New()
        DD_Data = New D_IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO
    End Sub
    Function IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO_() As List(Of E_IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO)
        Return DD_Data.IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO_()
    End Function
    Function IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO() As List(Of E_IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO)
        Return DD_Data.IRIS_QC_BUSCA_LOTE_ACTIVO_DESACTIVO()
    End Function
End Class
