Imports Entidades
Imports Datos
Public Class N_IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20
    Dim DD_Data As D_IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20
    Sub New()
        DD_Data = New D_IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20
    End Sub
    Function IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20(ByVal ID_ANA As Long, ByVal ID_LOTE As Long, ByVal ID_DET As Long) As List(Of E_IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20)
        Return DD_Data.IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20(ID_ANA, ID_LOTE, ID_DET)
    End Function
    Function IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_2(ByVal ID_ANA As Long, ByVal ID_LOTE As Long, ByVal ID_DET As Long, ByVal FECHA As String, ByVal N As Long) As List(Of E_IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_2)
        Return DD_Data.IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_2(ID_ANA, ID_LOTE, ID_DET, FECHA, N)
    End Function
    Function IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_ULT(ByVal ID_ANA As Long, ByVal ID_LOTE As Long, ByVal ID_DET As Long, ByVal N As Long) As List(Of E_IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_2)
        Return DD_Data.IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_ULT(ID_ANA, ID_LOTE, ID_DET, N)
    End Function
    Function IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_FECHA(ByVal ID_ANA As Long, ByVal ID_LOTE As Long, ByVal ID_DET As Long, ByVal DESDE As String, ByVal HASTA As String) As List(Of E_IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_2)
        Return DD_Data.IRIS_QC_BUSCA_DATOS_RESULTADO_POR_CRITERIOS20_FECHA(ID_ANA, ID_LOTE, ID_DET, DESDE, HASTA)
    End Function
End Class
