'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEB_BUSCA_USUARIO_ACTIVO_POR_PROCEDENCIA
    Dim DD_Data As D_IRIS_WEB_BUSCA_USUARIO_ACTIVO_POR_PROCEDENCIA
    Sub New()
        DD_Data = New D_IRIS_WEB_BUSCA_USUARIO_ACTIVO_POR_PROCEDENCIA
    End Sub
    Function IRIS_WEB_BUSCA_USUARIO_ACTIVO_POR_PROCEDENCIA(ByVal ID_PROCEDENCIA As Long) As List(Of E_IRIS_WEB_BUSCA_USUARIO_ACTIVO_POR_PROCEDENCIA)
        Return DD_Data.IRIS_WEB_BUSCA_USUARIO_ACTIVO_POR_PROCEDENCIA(ID_PROCEDENCIA)
    End Function
End Class
