Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_OBSERVACIONES_TOMA_MUESTRA_ATENCION
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_OBSERVACIONES_TOMA_MUESTRA_ATENCION
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_OBSERVACIONES_TOMA_MUESTRA_ATENCION
    End Sub
    Function IRIS_WEBF_BUSCA_OBSERVACIONES_TOMA_MUESTRA_ATENCION(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_OBSERVACIONES_TOMA_MUESTRA_ATENCION)
        Return DD_Data.IRIS_WEBF_BUSCA_OBSERVACIONES_TOMA_MUESTRA_ATENCION(ID_ATE)
    End Function

End Class
