'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION
    End Sub

    Function IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_PARTICULAR_BONIFICACION(ByVal ANO As String, ByVal ID_PREVE As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_PARTICULAR_BONIFICACION(ANO, ID_PREVE)
    End Function

    Function IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_BONIFICACION(ByVal ANO As String, ByVal ID_PREVE As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_BONIFICACION(ANO, ID_PREVE)
    End Function
    Function IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION(ByVal ANO As String, ByVal ID_PREVE As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION(ANO, ID_PREVE)
    End Function

    Function IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_SAN_JOAQUIN(ByVal ANO As String, ByVal ID_PREVE As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_SAN_JOAQUIN(ANO, ID_PREVE)
    End Function

    Function IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_22() As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_22()
    End Function
    Function IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_REL_ORDEN(ByVal ANO As String, ByVal ID_PREVE As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_REL_ORDEN(ANO, ID_PREVE)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_BONIFICACION_CF_PART_TIPO(ByVal ANO As String, ByVal ID_PREVE As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_BONIFICACION_CF_PART_TIPO(ANO, ID_PREVE)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_PARTICULAR_BONIFICACION_CF_PART_CF(ByVal ANO As String, ByVal ID_PREVE As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_PARTICULAR_BONIFICACION_CF_PART_CF(ANO, ID_PREVE)
    End Function

    Function IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_BONIFICACION_ID_CODIGO_FONASA(ByVal Fecha As String, ByVal ID_PREVE As Integer, ByVal ID_CF As Integer, ByVal ID_CF_REAL As Integer) As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_CODIGO_FONASA_PARA_CARGA_ATENCION_BONIFICACION_ID_CODIGO_FONASA(Fecha, ID_PREVE, ID_CF, ID_CF_REAL)
    End Function


End Class
