Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_CODIGO_FONASA
    Private DD_Data As D_IRIS_WEBF_BUSCA_CODIGO_FONASA
    Public Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_CODIGO_FONASA
    End Sub
    Function IRIS_WEBF_BUSCA_CODIGO_FONASA() As List(Of E_IRIS_WEBF_BUSCA_CODIGO_FONASA)
        Return DD_Data.D_IRIS_WEBF_BUSCA_CODIGO_FONASA()
    End Function

    Function LLENAR_TABLA_CODIGO_FONASA_ESTUDIO(ID_FONASA) As List(Of E_IRIS_WEBF_BUSCA_PER_FONASA_RELACION)
        Return DD_Data.LLENAR_TABLA_CODIGO_FONASA_ESTUDIO(ID_FONASA)
    End Function

    Function LLENAR_TABLA_CODIGO_FONASA_ESTUDIO_SIN_ID() As List(Of E_IRIS_WEBF_BUSCA_PER_FONASA_RELACION)
        Return DD_Data.LLENAR_TABLA_CODIGO_FONASA_ESTUDIO_SIN_ID()
    End Function

End Class
