Imports Entidades
Imports Datos
Public Class N_IRIS_WEBF_BUSCA_AGRUPACION_MANTENEDOR
    Private DD_Data As D_IRIS_WEBF_BUSCA_AGRUPACION_MANTENEDOR
    Public Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_AGRUPACION_MANTENEDOR
    End Sub
    Function IRIS_WEBF_BUSCA_AGRUPACION_MANTENEDOR() As List(Of E_IRIS_WEBF_BUSCA_AGRUPACION_MANTENEDOR)
        Return DD_Data.D_IRIS_WEBF_BUSCA_AGRUPACION_MANTENEDOR()
    End Function
End Class
