'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_BUSCA_ANTECENDES_PACIENTE_RECEP_ENVIO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_ANTECENDES_PACIENTE_RECEP_ENVIO

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_ANTECENDES_PACIENTE_RECEP_ENVIO
    End Sub

    Function IRIS_WEBF_BUSCA_ANTECENDES_PACIENTE_RECEP_ENVIO(ByVal NUM_ATE As String) As List(Of E_IRIS_WEBF_BUSCA_ANTECENDES_PACIENTE_RECEP_ENVIO)
        Return DD_Data.IRIS_WEBF_BUSCA_ANTECENDES_PACIENTE_RECEP_ENVIO(NUM_ATE)

    End Function
End Class