Imports Entidades
Imports Datos
Public Class N_IRIS_WEBF_BUSCA_HOJA_DE_TRABAJO_DE_SECCION_FECHA_AREA_DERIVADO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_HOJA_DE_TRABAJO_DE_SECCION_FECHA_AREA_DERIVADO

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_HOJA_DE_TRABAJO_DE_SECCION_FECHA_AREA_DERIVADO
    End Sub

    Function IRIS_WEBF_BUSCA_HOJA_DE_TRABAJO_DE_SECCION_FECHA_AREA_DERIVADO(ByVal DESDE As Date, ByVal HASTA As Date, ByVal ID_TP_PAGO As Integer) As List(Of E_IRIS_WEBF_BUSCA_HOJA_DE_TRABAJO_DE_SECCION_FECHA_AREA_DERIVADO)
        Return DD_Data.IRIS_WEBF_BUSCA_HOJA_DE_TRABAJO_DE_SECCION_FECHA_AREA_DERIVADO(DESDE, HASTA, ID_TP_PAGO)
    End Function
End Class
