'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_DETERMINACIONES_POR_CODIGO_FONASA_EST
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_DETERMINACIONES_POR_CODIGO_FONASA_EST
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_DETERMINACIONES_POR_CODIGO_FONASA_EST
    End Sub
    Function IRIS_WEBF_BUSCA_DETERMINACIONES_POR_CODIGO_FONASA_EST(ByVal ID_CF As Integer) As List(Of E_IRIS_WEBF_BUSCA_DETERMINACIONES_POR_CODIGO_FONASA_EST)
        Return DD_Data.IRIS_WEBF_BUSCA_DETERMINACIONES_POR_CODIGO_FONASA_EST(ID_CF)
    End Function
End Class