'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_BUSCA_EXAMEN_DET_ESTADISTICA_CHECK_TODOS
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_BUSCA_EXAMEN_DET_ESTADISTICA_CHECK_TODOS
    Sub New()
        DD_Data = New D_IRIS_BUSCA_EXAMEN_DET_ESTADISTICA_CHECK_TODOS
    End Sub
    Function IRIS_BUSCA_EXAMEN_DET_ESTADISTICA_CHECK_TODOS(ByVal DESDE As Date, ByVal HASTA As Date, ByVal ID_CF As Integer, ByVal ID_PRUEBA As Integer) As List(Of E_IRIS_BUSCA_EXAMEN_DET_ESTADISTICA_CHECK_TODOS)
        Return DD_Data.IRIS_BUSCA_EXAMEN_DET_ESTADISTICA_CHECK_TODOS(DESDE, HASTA, ID_CF, ID_PRUEBA)
    End Function
End Class