'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_BUSCA_ETIQUETA_RECEPCION_EN_PROCESO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_ETIQUETA_RECEPCION_EN_PROCESO

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_ETIQUETA_RECEPCION_EN_PROCESO
    End Sub

    Function IRIS_WEBF_BUSCA_ETIQUETA_RECEPCION_EN_PROCESO(ByVal FOLIO_NUM As Integer, ByVal NUM_CURVA As String) As List(Of E_IRIS_WEBF_BUSCA_ETIQUETA_RECEPCION_EN_PROCESO)
        Return DD_Data.IRIS_WEBF_BUSCA_ETIQUETA_RECEPCION_EN_PROCESO(FOLIO_NUM, NUM_CURVA)

    End Function
End Class