'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_BUSCA_CANTIDAD_LOTE_RECEPCIONADO
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_CANTIDAD_LOTE_RECEPCIONADO

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_CANTIDAD_LOTE_RECEPCIONADO
    End Sub

    Function IRIS_WEBF_BUSCA_CANTIDAD_LOTE_RECEPCIONADO() As List(Of E_IRIS_WEBF_BUSCA_CANTIDAD_LOTE_RECEPCIONADO)
        Return DD_Data.IRIS_WEBF_BUSCA_CANTIDAD_LOTE_RECEPCIONADO()

    End Function
End Class