'Importar Capas
Imports Datos
Imports Entidades

Public Class N_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_VER
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_VER

    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_VER
    End Sub

    Function IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_VER(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_VER)
        Return DD_Data.IRIS_WEBF_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_VER(ID_ATE)

    End Function
End Class