'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION

    Sub New()
        DD_Data = New D_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION
    End Sub

    Function IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION(ByVal ID_ATE As Integer, ByVal ID_USUARIO As Integer) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION(ID_ATE, ID_USUARIO)

    End Function

    Shared Function IRIS_WEB_GRABA_RECEPCION_ETIQUETA_Y_UPDATE_ATE_RESULTADO(ID_ATE As Integer, NUM_ATE As Integer, CB As String, ID_USU As Integer) As Integer
        Return D_IRIS_WEBF_UPDATE_ESTADO_RECEPCIONADO_RECEPCION.IRIS_WEB_GRABA_RECEPCION_ETIQUETA_Y_UPDATE_ATE_RESULTADO(ID_ATE, NUM_ATE, CB, ID_USU)
    End Function
End Class
