'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2
    Sub New()
        DD_Data = New D_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2
    End Sub
    Function IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_POR_DNI_NEW(ByVal ID_ATE As String) As List(Of E_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2)
        Return DD_Data.IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_POR_DNI_NEW(ID_ATE)
    End Function
    Function IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2)
        Return DD_Data.IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2(ID_ATE)
    End Function
    Function IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2_ATE(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2)
        Return DD_Data.IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2_ATE(ID_ATE)
    End Function

    Function IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_POR_RUT_NEW(ByVal ID_ATE As String) As List(Of E_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2)
        Return DD_Data.IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_POR_RUT_NEW(ID_ATE)
    End Function
    Function IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_NEW(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2)
        Return DD_Data.IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_NEW(ID_ATE)
    End Function

    Function IRIS_WEBF_BUSCA_DATOS_ATENCION_REIMPR(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_BUSCA_DATOS_ATENCION_REIMPR)
        Return DD_Data.E_IRIS_WEBF_BUSCA_DATOS_ATENCION_REIMPR(ID_ATE)
    End Function

    Function IRIS_WEBF_UPDATE_OBS_INTERNO_ATENCION(ByVal ID_ATE As String, ByVal N_INTERNO As String, ByVal OBS_TOMA As String, ByVal OBS_PAC As String) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_OBS_INTERNO_ATENCION(ID_ATE, N_INTERNO, OBS_TOMA, OBS_PAC)
    End Function


    Function IRIS_WEBF_UPDATE_ELIMINAR_ATENCION(ByVal ID_ATE As String) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_ELIMINAR_ATENCION(ID_ATE)
    End Function

    Function IRIS_WEBF_UPDATE_OBS_INTERNO_PRE_INGRESO(ByVal ID_ATE As String, ByVal N_INTERNO As String, ByVal OBS_TOMA As String, ByVal OBS_PAC As String) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_OBS_INTERNO_PRE_INGRESO(ID_ATE, N_INTERNO, OBS_TOMA, OBS_PAC)
    End Function
    Function IRIS_WEBF_UPDATE_ELIMINAR_PREINGRESO(ByVal ID_ATE As String) As Integer
        Return DD_Data.IRIS_WEBF_UPDATE_ELIMINAR_PREINGRESO(ID_ATE)
    End Function

    Shared Function IRIS_WEBF_UPDATE_PREINGRESO_NO_ASISITIO(ID_PREINGRESO As Integer) As Integer
        Return D_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2.IRIS_WEBF_UPDATE_PREINGRESO_NO_ASISITIO(ID_PREINGRESO)
    End Function
    Function IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_POR_DNI_NEW_2(ByVal ID_ATE As String) As List(Of E_IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES2)
        Return DD_Data.IRIS_WEBF_AGENDA_BUSCA_MUESTRA_ANTECEDENTES_PACIENTES_2_POR_DNI_NEW_2(ID_ATE)
    End Function
End Class