'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_GRABA_PREINGRESO2_PRO_SEC
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_GRABA_PREINGRESO2_PRO_SEC
    Sub New()
        DD_Data = New D_IRIS_WEBF_GRABA_PREINGRESO2_PRO_SEC
    End Sub
    Function IRIS_WEBF_GRABA_PREINGRESO2_PRO_SEC(ByVal ATE_NUM As String,
                                                 ByVal ID_PACIENTE As Integer,
                                                 ByVal ID_USUARIO As Integer,
                                                 ByVal ATE_FUR As Date,
                                                 ByVal ID_PROCE As Integer,
                                                 ByVal ID_ORDEN As Integer,
                                                 ByVal ID_TP_PACI As Integer,
                                                 ByVal ID_DOCTOR As Integer,
                                                 ByVal ID_PREVE As Integer,
                                                 ByVal ID_LOCAL As Integer,
                                                 ByVal ID_ESTADO As Integer,
                                                 ByVal ATE_OBS As String,
                                                 ByVal ATE_CAMA As String,
                                                 ByVal ATE_AÑO As Integer,
                                                 ByVal ATE_MES As Integer,
                                                 ByVal ATE_DIA As Integer,
                                                 ByVal ATE_TOTAL As Integer,
                                                 ByVal ATE_TOTAL_PREVI As Integer,
                                                 ByVal ATE_TOTAL_COPA As Integer,
                                                 ByVal PREI_FECHA_PRE As Date,
                                                 ByVal PROGRAMA As Integer,
                                                 ByVal SECTOR As Integer,
                                                 ByVal Diag As String,
                                                 ByVal Diag2 As String,
                                                 Optional ByVal xHora As String = "00:00") As Integer
        Return DD_Data.IRIS_WEBF_GRABA_PREINGRESO2_PRO_SEC(ATE_NUM,
                                                           ID_PACIENTE,
                                                           ID_USUARIO,
                                                           ATE_FUR,
                                                           ID_PROCE,
                                                           ID_ORDEN,
                                                           ID_TP_PACI,
                                                           ID_DOCTOR,
                                                           ID_PREVE,
                                                           ID_LOCAL,
                                                           ID_ESTADO,
                                                           ATE_OBS,
                                                           ATE_CAMA,
                                                           ATE_AÑO,
                                                           ATE_MES, ATE_DIA, ATE_TOTAL, ATE_TOTAL_PREVI, ATE_TOTAL_COPA, PREI_FECHA_PRE, PROGRAMA, SECTOR, Diag, Diag2, xHora)

    End Function


    Function IRIS_WEBF_GRABA_PREINGRESO2_PRO_SEC_NEW(ByVal ATE_NUM As String,
                                                 ByVal ID_PACIENTE As Integer,
                                                 ByVal ID_USUARIO As Integer,
                                                 ByVal ATE_FUR As Date,
                                                 ByVal ID_PROCE As Integer,
                                                 ByVal ID_ORDEN As Integer,
                                                 ByVal ID_TP_PACI As Integer,
                                                 ByVal ID_DOCTOR As Integer,
                                                 ByVal ID_PREVE As Integer,
                                                 ByVal ID_LOCAL As Integer,
                                                 ByVal ID_ESTADO As Integer,
                                                 ByVal ATE_OBS As String,
                                                 ByVal ATE_CAMA As String,
                                                 ByVal ATE_AÑO As Integer,
                                                 ByVal ATE_MES As Integer,
                                                 ByVal ATE_DIA As Integer,
                                                 ByVal ATE_TOTAL As Integer,
                                                 ByVal ATE_TOTAL_PREVI As Integer,
                                                 ByVal ATE_TOTAL_COPA As Integer,
                                                 ByVal PREI_FECHA_PRE As Date,
                                                 ByVal PROGRAMA As Integer,
                                                 ByVal SECTOR As Integer,
                                                 ByVal Diag As String,
                                                 ByVal Diag2 As String,
                                                     ByVal SUB_ATENCION As String,
                                                     ByVal vih As String,
                                                     ByVal dni As String,
                                                 Optional ByVal xHora As String = "00:00") As Integer
        Return DD_Data.IRIS_WEBF_GRABA_PREINGRESO2_PRO_SEC_NEW(ATE_NUM,
                                                           ID_PACIENTE,
                                                           ID_USUARIO,
                                                           ATE_FUR,
                                                           ID_PROCE,
                                                           ID_ORDEN,
                                                           ID_TP_PACI,
                                                           ID_DOCTOR,
                                                           ID_PREVE,
                                                           ID_LOCAL,
                                                           ID_ESTADO,
                                                           ATE_OBS,
                                                           ATE_CAMA,
                                                           ATE_AÑO,
                                                           ATE_MES, ATE_DIA, ATE_TOTAL, ATE_TOTAL_PREVI, ATE_TOTAL_COPA, PREI_FECHA_PRE, PROGRAMA, SECTOR, Diag, Diag2, SUB_ATENCION, vih, dni, xHora)

    End Function


    Function IRIS_WEBF_GRABA_PREINGRESO3_PRO_SEC_AVIS_NEW(ByVal ATE_NUM As String,
                                                 ByVal ID_PACIENTE As Integer,
                                                 ByVal ID_USUARIO As Integer,
                                                 ByVal ATE_FUR As Date,
                                                 ByVal ID_PROCE As Integer,
                                                 ByVal ID_ORDEN As Integer,
                                                 ByVal ID_TP_PACI As Integer,
                                                 ByVal ID_DOCTOR As Integer,
                                                 ByVal ID_PREVE As Integer,
                                                 ByVal ID_LOCAL As Integer,
                                                 ByVal ID_ESTADO As Integer,
                                                 ByVal ATE_OBS As String,
                                                 ByVal ATE_CAMA As String,
                                                 ByVal ATE_AÑO As Integer,
                                                 ByVal ATE_MES As Integer,
                                                 ByVal ATE_DIA As Integer,
                                                 ByVal ATE_TOTAL As Integer,
                                                 ByVal ATE_TOTAL_PREVI As Integer,
                                                 ByVal ATE_TOTAL_COPA As Integer,
                                                 ByVal PREI_FECHA_PRE As Date,
                                                 ByVal PROGRAMA As Integer,
                                                 ByVal SECTOR As Integer,
                                                 ByVal ATE_SAYDEX As String,
                                                 ByVal DIAG1 As Integer,
                                                 ByVal DIAG2 As Integer,
                                                 ByVal sub_atencion As String, ByVal vih As String, ByVal Sub_prgrama As String, ByVal EMPRESA As Integer,
                                                          ByVal ID_GRUPO_PESQUISA As Integer,
                                                 Optional ByVal xHora As String = "00:00") As Integer
        Return DD_Data.IRIS_WEBF_GRABA_PREINGRESO3_PRO_SEC_AVIS_NEW(ATE_NUM,
                                                           ID_PACIENTE,
                                                           ID_USUARIO,
                                                           ATE_FUR,
                                                           ID_PROCE,
                                                           ID_ORDEN,
                                                           ID_TP_PACI,
                                                           ID_DOCTOR,
                                                           ID_PREVE,
                                                           ID_LOCAL,
                                                           ID_ESTADO,
                                                           ATE_OBS,
                                                           ATE_CAMA,
                                                           ATE_AÑO,
                                                           ATE_MES, ATE_DIA, ATE_TOTAL, ATE_TOTAL_PREVI, ATE_TOTAL_COPA, PREI_FECHA_PRE, PROGRAMA, SECTOR, ATE_SAYDEX, DIAG1, DIAG2, sub_atencion, vih, Sub_prgrama, EMPRESA, ID_GRUPO_PESQUISA, xHora)

    End Function

    Function IRIS_WEBF_GRABA_PREINGRESO3_PRO_SEC_SAYDEX_NEW(ByVal ATE_NUM As String,
                                                 ByVal ID_PACIENTE As Integer,
                                                 ByVal ID_USUARIO As Integer,
                                                 ByVal ATE_FUR As Date,
                                                 ByVal ID_PROCE As Integer,
                                                 ByVal ID_ORDEN As Integer,
                                                 ByVal ID_TP_PACI As Integer,
                                                 ByVal ID_DOCTOR As Integer,
                                                 ByVal ID_PREVE As Integer,
                                                 ByVal ID_LOCAL As Integer,
                                                 ByVal ID_ESTADO As Integer,
                                                 ByVal ATE_OBS As String,
                                                 ByVal ATE_CAMA As String,
                                                 ByVal ATE_AÑO As Integer,
                                                 ByVal ATE_MES As Integer,
                                                 ByVal ATE_DIA As Integer,
                                                 ByVal ATE_TOTAL As Integer,
                                                 ByVal ATE_TOTAL_PREVI As Integer,
                                                 ByVal ATE_TOTAL_COPA As Integer,
                                                 ByVal PREI_FECHA_PRE As Date,
                                                 ByVal PROGRAMA As Integer,
                                                 ByVal SECTOR As Integer,
                                                 ByVal ATE_SAYDEX As String,
                                                 ByVal DIAG1 As Integer,
                                                 ByVal DIAG2 As Integer,
                                                      ByVal sub_atencion As String, ByVal vih As String,
                                                 Optional ByVal xHora As String = "00:00") As Integer
        Return DD_Data.IRIS_WEBF_GRABA_PREINGRESO3_PRO_SEC_SAYDEX_NEW(ATE_NUM,
                                                           ID_PACIENTE,
                                                           ID_USUARIO,
                                                           ATE_FUR,
                                                           ID_PROCE,
                                                           ID_ORDEN,
                                                           ID_TP_PACI,
                                                           ID_DOCTOR,
                                                           ID_PREVE,
                                                           ID_LOCAL,
                                                           ID_ESTADO,
                                                           ATE_OBS,
                                                           ATE_CAMA,
                                                           ATE_AÑO,
                                                           ATE_MES, ATE_DIA, ATE_TOTAL, ATE_TOTAL_PREVI, ATE_TOTAL_COPA, PREI_FECHA_PRE, PROGRAMA, SECTOR, ATE_SAYDEX, DIAG1, DIAG2, sub_atencion, vih, xHora)

    End Function

    Function IRIS_WEBF_GRABA_PREINGRESO3_PRO_SEC_AVIS(ByVal ATE_NUM As String,
                                                 ByVal ID_PACIENTE As Integer,
                                                 ByVal ID_USUARIO As Integer,
                                                 ByVal ATE_FUR As Date,
                                                 ByVal ID_PROCE As Integer,
                                                 ByVal ID_ORDEN As Integer,
                                                 ByVal ID_TP_PACI As Integer,
                                                 ByVal ID_DOCTOR As Integer,
                                                 ByVal ID_PREVE As Integer,
                                                 ByVal ID_LOCAL As Integer,
                                                 ByVal ID_ESTADO As Integer,
                                                 ByVal ATE_OBS As String,
                                                 ByVal ATE_CAMA As String,
                                                 ByVal ATE_AÑO As Integer,
                                                 ByVal ATE_MES As Integer,
                                                 ByVal ATE_DIA As Integer,
                                                 ByVal ATE_TOTAL As Integer,
                                                 ByVal ATE_TOTAL_PREVI As Integer,
                                                 ByVal ATE_TOTAL_COPA As Integer,
                                                 ByVal PREI_FECHA_PRE As Date,
                                                 ByVal PROGRAMA As Integer,
                                                 ByVal SECTOR As Integer,
                                                 ByVal ATE_SAYDEX As String,
                                                 ByVal DIAG1 As Integer,
                                                 ByVal DIAG2 As Integer,
                                                 Optional ByVal xHora As String = "00:00") As Integer
        Return DD_Data.IRIS_WEBF_GRABA_PREINGRESO3_PRO_SEC_AVIS(ATE_NUM,
                                                           ID_PACIENTE,
                                                           ID_USUARIO,
                                                           ATE_FUR,
                                                           ID_PROCE,
                                                           ID_ORDEN,
                                                           ID_TP_PACI,
                                                           ID_DOCTOR,
                                                           ID_PREVE,
                                                           ID_LOCAL,
                                                           ID_ESTADO,
                                                           ATE_OBS,
                                                           ATE_CAMA,
                                                           ATE_AÑO,
                                                           ATE_MES, ATE_DIA, ATE_TOTAL, ATE_TOTAL_PREVI, ATE_TOTAL_COPA, PREI_FECHA_PRE, PROGRAMA, SECTOR, ATE_SAYDEX, DIAG1, DIAG2, xHora)

    End Function
End Class