'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS
    Sub New()
        DD_Data = New D_IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS
    End Sub
    Function IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS(ByVal HOST As String) As List(Of E_IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS)
        Return DD_Data.IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS(HOST)
    End Function
    Function IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_SAYDEX(ByVal HOST As String) As List(Of E_IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS)
        Return DD_Data.IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_SAYDEX(HOST)
    End Function

    Function IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_OMI_PER(ByVal HOST As String) As List(Of E_IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS)
        Return DD_Data.IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_OMI_PER(HOST)
    End Function

    Function IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS_PER(ByVal HOST As String) As List(Of E_IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS)
        Return DD_Data.IRIS_WEBF_HOST_BUSCA_CODIGO_FONSA_POR_COD_AVIS_PER(HOST)
    End Function
End Class