'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_PERFIL_PRUEBA_ATENCION
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_PERFIL_PRUEBA_ATENCION
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_PERFIL_PRUEBA_ATENCION
    End Sub
    Function IRIS_WEBF_BUSCA_PERFIL_PRUEBA_ATENCION(ByVal ID_PER As Integer) As List(Of E_IRIS_WEBF_BUSCA_PERFIL_PRUEBA_ATENCION)
        Return DD_Data.IRIS_WEBF_BUSCA_PERFIL_PRUEBA_ATENCION(ID_PER)
    End Function

    Function IRIS_BUSCA_UNIDAD_MEDIDA() As List(Of E_IRIS_WEBF_BUSCA_UNIDAD_MEDIDA_ACTIVO)
        Return DD_Data.IRIS_BUSCA_UNIDAD_MEDIDA()
    End Function

    Function IRIS_BUSCA_TP_RESULTADO() As List(Of E_IRIS_WEBF_BUSCA_TP_RESULTADO_ACTIVADO)
        Return DD_Data.IRIS_BUSCA_TP_RESULTADO()
    End Function
    Function IRIS_BUSCA_MUESTRA() As List(Of E_IRIS_WEBF_BUSCA_TP_RECIPIENTE)
        Return DD_Data.IRIS_BUSCA_MUESTRA()
    End Function

    Function IRIS_DELETE_PRUEBA(ByVal ID_PRUEBA As Integer) As String
        Return DD_Data.IRIS_DELETE_PRUEBA(ID_PRUEBA)
    End Function

    Function IRIS_BUSCA_TP_BACTERIO() As List(Of E_IRIS_WEBF_BUSCA_BACTERIO)
        Return DD_Data.IRIS_BUSCA_TP_BACTERIO()
    End Function
    Function IRIS_BUSCA_PRUEBAS_POR_CODIGO_PER(ByVal ID_PER As Integer) As List(Of E_PRUEBAS)
        Return DD_Data.IRIS_BUSCA_PRUEBAS_POR_CODIGO_PER(ID_PER)
    End Function

    Function IRIS_WEBF_BUSCA_PERFIL_ESTUDIO_CLINICO() As List(Of E_ESTUDIO_CLINICO)
        Return DD_Data.IRIS_WEBF_BUSCA_PERFIL_ESTUDIO_CLINICO()
    End Function
    Function IRIS_WEBF_GRABA_ESTUDIOS(PER_COD, PER_DESC, PER_CORTO, PER_HOST1, PER_HOST2, PER_BAC_EST, ID_ESTADO, ID_RLS_LS, PER_NUM_PRU) As String
        Return DD_Data.IRIS_WEBF_GRABA_ESTUDIOS(PER_COD, PER_DESC, PER_CORTO, PER_HOST1, PER_HOST2, PER_BAC_EST, ID_ESTADO, ID_RLS_LS, PER_NUM_PRU)
    End Function

    Function IRIS_WEBF_UPDATE_ESTUDIOS_PERFIL(ID_PER, PER_COD, PER_DESC, PER_CORTO, PER_HOST1, PER_HOST2, PER_BAC_EST, ID_ESTADO, ID_RLS_LS) As String
        Return DD_Data.IRIS_WEBF_UPDATE_ESTUDIOS_PERFIL(ID_PER, PER_COD, PER_DESC, PER_CORTO, PER_HOST1, PER_HOST2, PER_BAC_EST, ID_ESTADO, ID_RLS_LS)
    End Function

    Function IRIS_WEBF_UPDATE_PRUEBA(ID_PRUEBA, COD_P, DESC_P, CORTO_P, ID_UM_P, ID_TP_RESUL_P, ID_T_MUESTRA, ID_TP_BAC, ID_PER, ORDEN_P, SOLICITADOL_P, ID_USUARIO_P, FECHA_M, ID_ESTADO, NUM_DEC, PRU_P_CERO, REQ_RES_VAL, PRU_P_PUNTO) As String
        Return DD_Data.IRIS_WEBF_UPDATE_PRUEBA(ID_PRUEBA, COD_P, DESC_P, CORTO_P, ID_UM_P, ID_TP_RESUL_P, ID_T_MUESTRA, ID_TP_BAC, ID_PER, ORDEN_P, SOLICITADOL_P, ID_USUARIO_P, FECHA_M, ID_ESTADO, NUM_DEC, PRU_P_CERO, REQ_RES_VAL, PRU_P_PUNTO)
    End Function

    Function IRIS_WEBF_GRABA_PRUEBA(COD_P, DESC_P, CORTO_P, ID_UM_P, ID_TP_RESUL_P, ID_T_MUESTRA, ID_TP_BAC, ID_PER, ORDEN_P, SOLICITADOL_P, ID_USUARIO_P, ID_ESTADO, NUM_DEC, HOST_P, PRU_P_CERO, REQ_RES_VAL, PRU_P_PUNTO) As List(Of E_PRUEBAS)
        Return DD_Data.IRIS_WEBF_GRABA_PRUEBA(COD_P, DESC_P, CORTO_P, ID_UM_P, ID_TP_RESUL_P, ID_T_MUESTRA, ID_TP_BAC, ID_PER, ORDEN_P, SOLICITADOL_P, ID_USUARIO_P, ID_ESTADO, NUM_DEC, HOST_P, PRU_P_CERO, REQ_RES_VAL, PRU_P_PUNTO)
    End Function

    Function IRIS_UPDATE_DETERMINACIONES_PERFIL(ID_PER, DET) As String
        Return DD_Data.IRIS_UPDATE_DETERMINACIONES_PERFIL(ID_PER, DET)
    End Function

    Function IRIS_WEBF_GRABA_FORMATO(PER_COD, PER_DESC, ID_PER, ID_ESTADO) As String
        Return DD_Data.IRIS_WEBF_GRABA_FORMATO(PER_COD, PER_DESC, ID_PER, ID_ESTADO)
    End Function

    Function IRIS_WEBF_UPDATE_FORMATO(PER_COD, PER_DESC, ID_PER) As String
        Return DD_Data.IRIS_WEBF_UPDATE_FORMATO(PER_COD, PER_DESC, ID_PER)
    End Function

    Function IRIS_WEBF_DELETE_FORMATO(ID_PER) As String
        Return DD_Data.IRIS_WEBF_DELETE_FORMATO(ID_PER)
    End Function


    Function IRIS_WEBF_BUSCA_FORMATO(COD_P, ID_PER) As List(Of E_IRIS_WEBF_BUSCA_FORMATO)
        Return DD_Data.IRIS_WEBF_BUSCA_FORMATO(COD_P, ID_PER)
    End Function

    Function IRIS_WEBF_GRABA_FORMATO_RESULTADO(ID_FORMATO, FR_OBJETO, FR_ID_OBJETO, FR_FILA, FR_COLUMNA, FR_ALTO, FR_ANCHO, FR_TEXTO, ID_LETRA, FR_TAMANO, FR_EFECTO, FR_DINAMICA, FR_DEPENDENCIA, ID_PRUEBA, ID_ESTADO) As String
        Return DD_Data.IRIS_WEBF_GRABA_FORMATO_RESULTADO(ID_FORMATO, FR_OBJETO, FR_ID_OBJETO, FR_FILA, FR_COLUMNA, FR_ALTO, FR_ANCHO, FR_TEXTO, ID_LETRA, FR_TAMANO, FR_EFECTO, FR_DINAMICA, FR_DEPENDENCIA, ID_PRUEBA, ID_ESTADO)
    End Function

    Function IRIS_WEBF_UPDATE_FORMATO_RESULTADO(FR_OBJETO, FR_TEXTO, FR_TEXTOANT, FR_UNIDAD, ID_PRUEBA) As String
        Return DD_Data.IRIS_WEBF_UPDATE_FORMATO_RESULTADO(FR_OBJETO, FR_TEXTO, FR_TEXTOANT, FR_UNIDAD, ID_PRUEBA)
    End Function

    Function IRIS_WEBF_DELETE_FORMATO_RESULTADO(ID_PRUEBA) As String
        Return DD_Data.IRIS_WEBF_DELETE_FORMATO_RESULTADO(ID_PRUEBA)
    End Function


    '------------------------------------------ REFER ---------------------------------------------------------------'

    Function IRIS_BUSCA_RANGO_REFERENCIA(ByVal ID_DET As Integer) As List(Of E_IRIS_BUSCA_RANGO_REFERENCIA)
        Return DD_Data.IRIS_BUSCA_RANGO_REFERENCIA(ID_DET)
    End Function

End Class