'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_AGENDA_BUSCA_NUM_ATE_POR_ID_ATENCION
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_AGENDA_BUSCA_NUM_ATE_POR_ID_ATENCION

    Sub New()
        DD_Data = New D_IRIS_WEBF_AGENDA_BUSCA_NUM_ATE_POR_ID_ATENCION
    End Sub

    Function IRIS_WEBF_AGENDA_BUSCA_NUM_ATE_POR_ID_ATENCION(ByVal ID_ATE As Integer) As List(Of E_IRIS_WEBF_AGENDA_BUSCA_NUM_ATE_POR_ID_ATENCION)
        Return DD_Data.IRIS_WEBF_AGENDA_BUSCA_NUM_ATE_POR_ID_ATENCION(ID_ATE)

    End Function
End Class
