'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS
    Sub New()
        DD_Data = New D_IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS
    End Sub
    Shared Function IRIS_WEBF_ELIMINA_EXAMEN_ATE_RESULTADO_UPDATE_VALOR_ATE_GRABA_HISTORIAL(ID_ATENCION As Integer,
                                                                                                   ID_CODIGO_FONASA As Integer,
                                                                                                   ID_USUARIO As Integer) As Integer
        Return D_IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS.IRIS_WEBF_ELIMINA_EXAMEN_ATE_RESULTADO_UPDATE_VALOR_ATE_GRABA_HISTORIAL(ID_ATENCION, ID_CODIGO_FONASA, ID_USUARIO)
    End Function

    Function IRIS_WEBF_GRABA_HISTORIA_ATENCION_AGREGA_QUITA(ID_ATENCION As Integer,
                                                            ID_CODIGO_FONASA As Integer,
                                                            ATE_TOTAL_OLD As Integer,
                                                            ATE_V_CF_OLD As Integer,
                                                            ATE_TOTAL_PREVI_OLD As Integer,
                                                            VALOR_PREVI_NEW As Integer,
                                                            VALOR_CF_NEW As Integer,
                                                            VALOR_PAGADO_NEW As Integer,
                                                            VALOR_PREVI_FINAL_NEW As Integer,
                                                            ID_ESTADO As Integer,
                                                            ID_USUARIO As Integer,
                                                            ID_DET_ATE As Integer) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_HISTORIA_ATENCION_AGREGA_QUITA(ID_ATENCION, ID_CODIGO_FONASA, ATE_TOTAL_OLD, ATE_V_CF_OLD, ATE_TOTAL_PREVI_OLD, VALOR_PREVI_NEW, VALOR_CF_NEW, VALOR_PAGADO_NEW, VALOR_PREVI_FINAL_NEW, ID_ESTADO, ID_USUARIO, ID_DET_ATE)
    End Function
    Function IRIS_WEBF_CMVM_GRABA_REL_COPAGO_2(ByVal ID_ATENCION As Integer,
                                            ByVal ID_USUARIO As Integer,
                                            ByVal ATE_FECHA As Date,
                                            ByVal ATE_TP_COPAGO_1 As String,
                                             ByVal ATE_VALOR_COPAGO_1 As String,
                                             ByVal ATE_TP_COPAGO_2 As String,
                                             ByVal ATE_VALOR_COPAGO_2 As String,
                                             ByVal ATE_V_CP_FP_2 As Integer,
                                             ByVal ATE_V_CP_2 As String,
                                             ByVal ATE_TP_PARTICULAR_1 As String,
                                             ByVal ATE_VALOR_PARTICULAR_1 As String,
                                             ByVal ATE_TP_PARTICULAR_2 As String,
                                             ByVal ATE_VALOR_PARTICULAR_2 As String,
                                               ByVal ORIGEN As String) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_REL_COPAGO_2(ID_ATENCION,
                                                       ID_USUARIO,
                                                       ATE_FECHA,
                                                       ATE_TP_COPAGO_1,
                                                       ATE_VALOR_COPAGO_1,
                                                       ATE_TP_COPAGO_2,
                                                       ATE_VALOR_COPAGO_2,
                                                       ATE_V_CP_FP_2,
                                                       ATE_V_CP_2,
                                                       ATE_TP_PARTICULAR_1,
                                                       ATE_VALOR_PARTICULAR_1,
                                                       ATE_TP_PARTICULAR_2,
                                                       ATE_VALOR_PARTICULAR_2,
                                                         ORIGEN)
    End Function

    Function IRIS_WEBF_CMVM_RESET_REL_COPAGO_BY_ID_ATENCION(ByVal ID_ATENCION As Integer) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_RESET_REL_COPAGO_BY_ID_ATENCION(ID_ATENCION)
    End Function

    Function IRIS_WEBF_CMVM_UPDATE_ATE_ELIMINAR_EXAMEN_DET_ATE_CAJA(ByVal ID_ATENCION As Integer,
                                                                ByVal ID_CODIGO_FONASA As Integer) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_UPDATE_ATE_ELIMINAR_EXAMEN_DET_ATE_CAJA(ID_ATENCION,
                                                                              ID_CODIGO_FONASA)
    End Function
    Function IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_CHANGE_TP_PAGO(ByVal ID_ATENCION As Integer,
                                                                                                    ByVal VALOR_PREVI As Integer,
                                                                                                    ByVal VALOR_BENEFI As Integer,
                                                                                                    ByVal VALOR_SC As Integer,
                                                                                                    ByVal VALOR_PAGADO As Integer,
                                                                                                    ByVal VALOR_CF As Integer,
                                                                                                    ByVal VALOR_CP As Integer) As Integer
        Return DD_Data.IRIS_WEBF_CMVM_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_CHANGE_TP_PAGO(ID_ATENCION,
                                                                                                              VALOR_PREVI,
                                                                                                              VALOR_BENEFI,
                                                                                                              VALOR_SC,
                                                                                                              VALOR_PAGADO,
                                                                                                              VALOR_CF,
                                                                                                              VALOR_CP)
    End Function
    Function IRIS_WEBF_BUSCA_REL_COPAGO_AGREGA_EXAMEN(ByVal ID_ATENCION As Integer) As List(Of E_IRIS_WEBF_BUSCA_RESUMEN_PREVE_PROG_SUBP)
        Return DD_Data.IRIS_WEBF_BUSCA_REL_COPAGO_AGREGA_EXAMEN(ID_ATENCION)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_DET_ATENCION_ELIMINA_EXAMEN(ByVal ID_ATENCION As Integer, ByVal ID_CODIGO_FONASA As Integer) As List(Of E_IRIS_WEBF_BUSCA_RESUMEN_PREVE_PROG_SUBP)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_DET_ATENCION_ELIMINA_EXAMEN(ID_ATENCION, ID_CODIGO_FONASA)
    End Function
    Function IRIS_WEBF_CMVM_BUSCA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_CHANGE_TP_PAGO(ByVal ID_ATENCION As Integer) As List(Of E_IRIS_WEBF_BUSCA_RESUMEN_PREVE_PROG_SUBP)
        Return DD_Data.IRIS_WEBF_CMVM_BUSCA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_CAJA_MAS_SC_CHANGE_TP_PAGO(ID_ATENCION)
    End Function
    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS(ByVal ATE_NUM As String,
                                                              ByVal ID_PACIENTE As Integer,
                                                              ByVal ID_USUARIO As Integer,
                                                              ByVal ATE_FUR As String,
                                                              ByVal ID_PROCE As Integer,
                                                              ByVal ID_ORDEN As Integer,
                                                              ByVal ID_TP_PACI As Integer,
                                                              ByVal ID_DOCTOR As Integer,
                                                              ByVal ID_PREVE As Integer,
                                                              ByVal ID_LOCAL As Integer,
                                                              ByVal ID_ESTADO As Integer,
                                                              ByVal ATE_OBS As String,
                                                              ByVal ATE_CAMA As String,
                                                              ByVal ATE_AÑO As Integer,
                                                              ByVal ATE_MES As Integer,
                                                              ByVal ATE_DIA As Integer,
                                                              ByVal ATE_TOTAL As Integer,
                                                              ByVal ATE_TOTAL_PREVI As Integer,
                                                              ByVal ATE_TOTAL_COPA As Integer,
                                                              ByVal ID_PROGRA As Integer,
                                                              ByVal ATE_RETIRO As String,
                                                              ByVal SECTOR As Integer,
                                                              ByVal ATE_AVIS As String,
                                                              ByVal Interno As String,
                                                              ByVal Diag As String,
                                                              ByVal Diag2 As String,
                                                              ByVal VIH As String,
                                                              ByVal dni As String,
                                                              ByVal ATE_TM As String,
                                                              ByVal SUB_PROGRAMA As String,
                                                              ByVal EPIVIGILA As String,
                                                              ByVal BUSQUEDA_ACTIVA As Integer,
                                                              ByVal EXAMED As String,
                                                              ByVal EMPRESA As Integer,
                                                              ByVal ID_GRUPO_PESQUISA As Integer) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                        ATE_TM, SUB_PROGRAMA,
                                                                        EPIVIGILA,
                                                                        BUSQUEDA_ACTIVA,
                                                                        EXAMED,
                                                                        EMPRESA,
                                                                        ID_GRUPO_PESQUISA)
    End Function

    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX(ByVal ATE_NUM As String,
                                                              ByVal ID_PACIENTE As Integer,
                                                              ByVal ID_USUARIO As Integer,
                                                              ByVal ATE_FUR As String,
                                                              ByVal ID_PROCE As Integer,
                                                              ByVal ID_ORDEN As Integer,
                                                              ByVal ID_TP_PACI As Integer,
                                                              ByVal ID_DOCTOR As Integer,
                                                              ByVal ID_PREVE As Integer,
                                                              ByVal ID_LOCAL As Integer,
                                                              ByVal ID_ESTADO As Integer,
                                                              ByVal ATE_OBS As String,
                                                              ByVal ATE_CAMA As String,
                                                              ByVal ATE_AÑO As Integer,
                                                              ByVal ATE_MES As Integer,
                                                              ByVal ATE_DIA As Integer,
                                                              ByVal ATE_TOTAL As Integer,
                                                              ByVal ATE_TOTAL_PREVI As Integer,
                                                              ByVal ATE_TOTAL_COPA As Integer,
                                                              ByVal ID_PROGRA As Integer,
                                                              ByVal ATE_RETIRO As String,
                                                              ByVal SECTOR As Integer,
                                                              ByVal ATE_AVIS As String,
                                                              ByVal Interno As String,
                                                              ByVal Diag As String,
                                                              ByVal Diag2 As String,
                                                              ByVal VIH As String,
                                                              ByVal dni As String) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni)
    End Function
    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_VIH_NEW(ByVal ATE_NUM As String,
                                                            ByVal ID_PACIENTE As Integer,
                                                            ByVal ID_USUARIO As Integer,
                                                            ByVal ATE_FUR As String,
                                                            ByVal ID_PROCE As Integer,
                                                            ByVal ID_ORDEN As Integer,
                                                            ByVal ID_TP_PACI As Integer,
                                                            ByVal ID_DOCTOR As Integer,
                                                            ByVal ID_PREVE As Integer,
                                                            ByVal ID_LOCAL As Integer,
                                                            ByVal ID_ESTADO As Integer,
                                                            ByVal ATE_OBS As String,
                                                            ByVal ATE_CAMA As String,
                                                            ByVal ATE_AÑO As Integer,
                                                            ByVal ATE_MES As Integer,
                                                            ByVal ATE_DIA As Integer,
                                                            ByVal ATE_TOTAL As Integer,
                                                            ByVal ATE_TOTAL_PREVI As Integer,
                                                            ByVal ATE_TOTAL_COPA As Integer,
                                                            ByVal ID_PROGRA As Integer,
                                                            ByVal ATE_RETIRO As String,
                                                            ByVal SECTOR As Integer,
                                                            ByVal ATE_AVIS As String,
                                                            ByVal Interno As String,
                                                            ByVal Diag As String,
                                                            ByVal Diag2 As String,
                                                            ByVal VIH As String,
                                                            ByVal dni As String,
                                                            ByVal ATE_TM As String,
                                                            ByVal NEW_VIH As String) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_AVIS_3_NEW_VIH_NEW(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni,
                                                                        ATE_TM,
                                                                        NEW_VIH)
    End Function

    Function IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX_POSTA(ByVal ATE_NUM As String,
                                                              ByVal ID_PACIENTE As Integer,
                                                              ByVal ID_USUARIO As Integer,
                                                              ByVal ATE_FUR As String,
                                                              ByVal ID_PROCE As Integer,
                                                              ByVal ID_ORDEN As Integer,
                                                              ByVal ID_TP_PACI As Integer,
                                                              ByVal ID_DOCTOR As Integer,
                                                              ByVal ID_PREVE As Integer,
                                                              ByVal ID_LOCAL As Integer,
                                                              ByVal ID_ESTADO As Integer,
                                                              ByVal ATE_OBS As String,
                                                              ByVal ATE_CAMA As String,
                                                              ByVal ATE_AÑO As Integer,
                                                              ByVal ATE_MES As Integer,
                                                              ByVal ATE_DIA As Integer,
                                                              ByVal ATE_TOTAL As Integer,
                                                              ByVal ATE_TOTAL_PREVI As Integer,
                                                              ByVal ATE_TOTAL_COPA As Integer,
                                                              ByVal ID_PROGRA As Integer,
                                                              ByVal ATE_RETIRO As String,
                                                              ByVal SECTOR As Integer,
                                                              ByVal ATE_AVIS As String,
                                                              ByVal Interno As String,
                                                              ByVal Diag As String,
                                                              ByVal Diag2 As String,
                                                              ByVal VIH As String,
                                                              ByVal dni As String) As Integer
        Return DD_Data.IRIS_WEBF_GRABA_ATENCION_PROGRA2_PRO_SECTOR_SAYDEX_POSTA(ATE_NUM,
                                                                        ID_PACIENTE,
                                                                        ID_USUARIO,
                                                                        ATE_FUR,
                                                                        ID_PROCE,
                                                                        ID_ORDEN,
                                                                        ID_TP_PACI,
                                                                        ID_DOCTOR,
                                                                        ID_PREVE,
                                                                        ID_LOCAL,
                                                                        ID_ESTADO,
                                                                        ATE_OBS,
                                                                        ATE_CAMA,
                                                                        ATE_AÑO,
                                                                        ATE_MES,
                                                                        ATE_DIA,
                                                                        ATE_TOTAL,
                                                                        ATE_TOTAL_PREVI,
                                                                        ATE_TOTAL_COPA,
                                                                        ID_PROGRA,
                                                                        ATE_RETIRO,
                                                                        SECTOR,
                                                                        ATE_AVIS,
                                                                        Interno,
                                                                         Diag, Diag2,
                                                                        VIH,
                                                                        dni)
    End Function
End Class