'Importar Capas
Imports Datos
Imports Entidades
Public Class N_IRIS_WEBF_BUSCA_RUT_PRE_INGRESO_PACIENTE_SIN_FECHA
    'Declaraciones Generales
    Dim DD_Data As D_IRIS_WEBF_BUSCA_RUT_PRE_INGRESO_PACIENTE_SIN_FECHA
    Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_RUT_PRE_INGRESO_PACIENTE_SIN_FECHA
    End Sub
    Function IRIS_WEBF_BUSCA_RUT_PRE_INGRESO_PACIENTE_SIN_FECHA(ByVal RUT As String) As List(Of E_IRIS_WEBF_BUSCA_RUT_PRE_INGRESO_PACIENTE_SIN_FECHA)
        Return DD_Data.IRIS_WEBF_BUSCA_RUT_PRE_INGRESO_PACIENTE_SIN_FECHA(RUT)
    End Function
End Class