Imports Entidades
Imports Datos
Public Class N_IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2
    Private DD_Data As D_IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2
    Public Sub New()
        DD_Data = New D_IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2
    End Sub
    Function IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2(ByVal ID_PRO As Integer, ByVal FECHA As String) As List(Of E_IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2)
        Return DD_Data.D_IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2(ID_PRO, FECHA)
    End Function
    Function IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2_NEW(ByVal ID_PRO As Integer, ByVal FECHA As String) As List(Of E_IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2)
        Return DD_Data.IRIS_WEBF_BUSCA_DIAS_CONF_ATENCIONES_PROCEDENCIA2_NEW(ID_PRO, FECHA)
    End Function
End Class
